### ISSUE TITLE
Build fails on OSX running go1.11.5

### ISSUE THREAD

**Issue by thedon-chris** [Eximchain/quorum#24]
#### System information

OS & Version: OSX

git HEAD = 4b03d73ce2c6ad841c5ba07ecc9f70066d3cf1cc

#### Expected behaviour
`make all` compiles fine on `jpmorganchase/quorum` 

#### Actual behaviour
`make all` fails on `Eximchain/quorum` 

#### Steps to reproduce the behaviour
<img width="696" alt="screen shot 2019-02-22 at 4 13 14 pm" src="https://user-images.githubusercontent.com/30728737/53271653-1b860e80-36bd-11e9-8580-1a589a84d944.png">

#### Backtrace

````
[backtrace]
````

**Comment by Lsquared13** [comment]
Hi @thedon-chris 

This is no longer the official Eximchain client and we are no longer maintaining this repository. We still have this around for testing and experimentation purposes, as the official Eximchain client does not yet support private transactions, but we were dissatisfied with some decisions made upstream and decided to base our client directly on go-ethereum. You can find the client we are currently using [here](https://github.com/Eximchain/go-ethereum)

Thank you for taking the time to file this issue
