### ISSUE TITLE
Bootnodes need to stay connected

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/quorum#9]
# Problem

It has come to our attention that, after being idle for too long, the bootnodes will completely disconnect from the network. This manifests as new nodes eventually being unable to find peers via our bootnode.

# Acceptance Criteria

- Nodes connecting to the network can reliably find peers through bootnodes regardless of how long the bootnode may have been inactive for.

**Comment by Lsquared13** [comment]
@eximchain137 If you have more context on this issue drop it here when you get the chance

**Comment by eximchain137** [comment]
TLDR; need to use full nodes as bootnodes (this is that ethereum does for mainnet and rinkeby) the bootnode command itself is not a full fledged node: currently there is no way to specify a network id so you can't add another node a few days after network genesis via bootnodes used to initially connect the network.


[https://github.com/ethereum/go-ethereum/issues/1685](url)

**Comment by john-osullivan** [comment]
Not sure if I'm misunderstanding the comment, @eximchain137 , but could this be resolved by just adding a `--network-id` option to `cmd/bootnode/main.go` and then passing it somewhere else?  Adding an option is pretty easy.

**Comment by Lsquared13** [comment]
We've decided bootnodes will just be for starting the network and other participants will be expected to join through our observer nodes. Closing this issue
